# Generated by Django 2.1.5 on 2019-02-25 14:57

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('assure', '0003_pilot_viewport_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='pilot',
            name='viewport_json',
            field=jsonfield.fields.JSONField(default=[]),
        ),
    ]
