# Generated by Django 2.1.5 on 2019-02-25 15:55

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('assure', '0005_remove_pilot_viewport_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='pilot',
            name='site_json',
            field=jsonfield.fields.JSONField(default=[]),
        ),
    ]
