# Generated by Django 2.1.5 on 2019-02-27 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assure', '0007_pilot_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='domain',
            field=models.CharField(default='', max_length=20),
        ),
    ]
