# Generated by Django 2.1.5 on 2019-03-02 22:02

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('assure', '0008_site_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='pilot',
            name='homepage_json',
            field=jsonfield.fields.JSONField(default=[]),
        ),
        migrations.AlterField(
            model_name='site',
            name='domain',
            field=models.CharField(default='a', max_length=20),
        ),
    ]
